language: erlang
addons:
  apt:
    packages:
      - libprotobuf-dev
      - protobuf-compiler
otp_release:
  - 20.3
  - 19.3
  - 18.3
  - 17.5
  - R16B03
  - R15B03
env:
  - VERBOSE=1
script:
  - make
  - make test
